version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: banktask
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: '1'
      DB_NAME: banktask
      DB_USER: root
      DB_PASSWORD: password@123
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
