# Generated by Django 5.1.2 on 2024-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flow_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10, null=True),
        ),
    ]
