# Generated by Django 5.1.2 on 2024-10-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_transaction_flow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('deposit', 'Deposit')], max_length=10),
        ),
    ]
