# Generated by Django 5.1.2 on 2024-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
