# Generated by Django 5.1.2 on 2024-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_is_active_customer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
